use_frameworks!

target 'AplhaVantageSwift_Example' do
  pod 'AplhaVantageSwift', :path => '../'

  target 'AplhaVantageSwift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
