use_frameworks!
inhibit_all_warnings!

def development_pods
    pod 'AplhaVantageSwift', :path => '../'
end

target 'AplhaVantageSwift-iOS' do
    platform :ios, 9.0

    development_pods

    target 'AplhaVantageSwift_Tests' do
        inherit! :search_paths

        pod 'Quick', '~> 1.2.0'
        pod 'Nimble', '~> 7.0.2'
    end
end

target 'AlphaVantageSwift-macOS' do
    platform :osx, 10.9

    development_pods
end
