use_frameworks!
inhibit_all_warnings!

def development_pods
    pod 'AplhaVantageSwift', :path => '../'
end

target 'AplhaVantageSwiftiOS' do
    platform :ios, 9.0

    development_pods
end

target 'AlphaVantageSwiftmacOS' do
    platform :osx, 10.9

    development_pods
end
